# Generated by Django 4.1.2 on 2022-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='uname',
            field=models.EmailField(max_length=254),
        ),
    ]
