# Generated by Django 4.1.2 on 2022-10-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_register_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='crud_app/static')),
            ],
        ),
    ]
